# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/ttlibc
pkgincludedir = $(includedir)/ttlibc
pkglibdir = $(libdir)/ttlibc
pkglibexecdir = $(libexecdir)/ttlibc
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin18.2.0
host_triplet = x86_64-apple-darwin18.2.0
target_triplet = x86_64-apple-darwin18.2.0
am__append_1 = \
	ttLibC/util/openalUtil.h

am__append_2 = \
	ttLibC/util/opencvUtil.h

am__append_3 = \
	ttLibC/encoder/mp3lameEncoder.h

am__append_4 = \
	ttLibC/decoder/mp3lameDecoder.h

am__append_5 = \
	ttLibC/encoder/faacEncoder.h

am__append_6 = \
	ttLibC/decoder/openh264Decoder.h \
	ttLibC/encoder/openh264Encoder.h

am__append_7 = \
	ttLibC/resampler/speexdspResampler.h

am__append_8 = \
	ttLibC/decoder/speexDecoder.h \
	ttLibC/encoder/speexEncoder.h

am__append_9 = \
	ttLibC/util/httpUtil.h \
	ttLibC/util/forkUtil.h

am__append_10 = \
	ttLibC/net/client/rtmp.h \
	ttLibC/net/client/websocket.h \
	ttLibC/net/net.h \
	ttLibC/net/tcp.h \
	ttLibC/net/tetty.h \
	ttLibC/net/udp.h \
	ttLibC/net/tetty2/tcpBootstrap.h

am__append_11 = \
	ttLibC/decoder/opusDecoder.h \
	ttLibC/encoder/opusEncoder.h

am__append_12 = \
	ttLibC/encoder/avcodecEncoder.h \
	ttLibC/decoder/avcodecDecoder.h

am__append_13 = \
	ttLibC/encoder/jpegEncoder.h \
	ttLibC/decoder/jpegDecoder.h

am__append_14 = \
	ttLibC/encoder/x264Encoder.h

am__append_15 = \
	ttLibC/encoder/x265Encoder.h

am__append_16 = \
	ttLibC/encoder/theoraEncoder.h \
	ttLibC/decoder/theoraDecoder.h

am__append_17 = \
	ttLibC/encoder/vorbisEncoder.h

am__append_18 = \
	ttLibC/decoder/vorbisDecoder.h

am__append_19 = \
	ttLibC/decoder/audioConverterDecoder.h \
	ttLibC/decoder/vtDecompressSessionDecoder.h \
	ttLibC/encoder/audioConverterEncoder.h \
	ttLibC/encoder/vtCompressSessionEncoder.h \
	ttLibC/util/audioUnitUtil.h

am__append_20 = \
	ttLibC/resampler/soundtouchResampler.h

am__append_21 = \
	ttLibC/resampler/libyuvResampler.h

am__append_22 = \
	ttLibC/resampler/swscaleResampler.h

am__append_23 = \
	ttLibC/resampler/swresampleResampler.h

am__append_24 = \
	ttLibC/decoder/pngDecoder.h

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__nobase_include_HEADERS_DIST) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = ttLibC.pc
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(pkgconfigdir)" \
	"$(DESTDIR)$(includedir)"
DATA = $(pkgconfig_DATA)
am__nobase_include_HEADERS_DIST = ttLibC/container/container.h \
	ttLibC/container/flv.h ttLibC/container/mkv.h \
	ttLibC/container/mp3.h ttLibC/container/mp4.h \
	ttLibC/container/mpegts.h ttLibC/frame/audio/aac.h \
	ttLibC/frame/audio/adpcmImaWav.h ttLibC/frame/audio/audio.h \
	ttLibC/frame/audio/mp3.h ttLibC/frame/audio/nellymoser.h \
	ttLibC/frame/audio/opus.h ttLibC/frame/audio/pcmAlaw.h \
	ttLibC/frame/audio/pcmf32.h ttLibC/frame/audio/pcmMulaw.h \
	ttLibC/frame/audio/pcms16.h ttLibC/frame/audio/speex.h \
	ttLibC/frame/audio/vorbis.h ttLibC/frame/video/bgr.h \
	ttLibC/frame/video/flv1.h ttLibC/frame/video/h264.h \
	ttLibC/frame/video/h265.h ttLibC/frame/video/jpeg.h \
	ttLibC/frame/video/png.h ttLibC/frame/video/theora.h \
	ttLibC/frame/video/video.h ttLibC/frame/video/vp6.h \
	ttLibC/frame/video/vp8.h ttLibC/frame/video/vp9.h \
	ttLibC/frame/video/wmv1.h ttLibC/frame/video/wmv2.h \
	ttLibC/frame/video/yuv420.h ttLibC/frame/frame.h \
	ttLibC/resampler/audioResampler.h \
	ttLibC/resampler/imageResampler.h \
	ttLibC/resampler/imageResizer.h ttLibC/util/amfUtil.h \
	ttLibC/util/beepUtil.h ttLibC/util/byteUtil.h \
	ttLibC/util/crc32Util.h ttLibC/util/dynamicBufferUtil.h \
	ttLibC/util/hexUtil.h ttLibC/util/ioUtil.h \
	ttLibC/util/stlListUtil.h ttLibC/util/stlMapUtil.h \
	ttLibC/util/tetty2.h ttLibC/allocator.h ttLibC/log.h \
	ttLibC/ttLibC.h ttLibC/util/openalUtil.h \
	ttLibC/util/opencvUtil.h ttLibC/encoder/mp3lameEncoder.h \
	ttLibC/decoder/mp3lameDecoder.h ttLibC/encoder/faacEncoder.h \
	ttLibC/decoder/openh264Decoder.h \
	ttLibC/encoder/openh264Encoder.h \
	ttLibC/resampler/speexdspResampler.h \
	ttLibC/decoder/speexDecoder.h ttLibC/encoder/speexEncoder.h \
	ttLibC/util/httpUtil.h ttLibC/util/forkUtil.h \
	ttLibC/net/client/rtmp.h ttLibC/net/client/websocket.h \
	ttLibC/net/net.h ttLibC/net/tcp.h ttLibC/net/tetty.h \
	ttLibC/net/udp.h ttLibC/net/tetty2/tcpBootstrap.h \
	ttLibC/decoder/opusDecoder.h ttLibC/encoder/opusEncoder.h \
	ttLibC/encoder/avcodecEncoder.h \
	ttLibC/decoder/avcodecDecoder.h ttLibC/encoder/jpegEncoder.h \
	ttLibC/decoder/jpegDecoder.h ttLibC/encoder/x264Encoder.h \
	ttLibC/encoder/x265Encoder.h ttLibC/encoder/theoraEncoder.h \
	ttLibC/decoder/theoraDecoder.h ttLibC/encoder/vorbisEncoder.h \
	ttLibC/decoder/vorbisDecoder.h \
	ttLibC/decoder/audioConverterDecoder.h \
	ttLibC/decoder/vtDecompressSessionDecoder.h \
	ttLibC/encoder/audioConverterEncoder.h \
	ttLibC/encoder/vtCompressSessionEncoder.h \
	ttLibC/util/audioUnitUtil.h \
	ttLibC/resampler/soundtouchResampler.h \
	ttLibC/resampler/libyuvResampler.h \
	ttLibC/resampler/swscaleResampler.h \
	ttLibC/resampler/swresampleResampler.h \
	ttLibC/decoder/pngDecoder.h
HEADERS = $(nobase_include_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/ttLibC.pc.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS README compile config.guess \
	config.sub depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/taktod/Documents/c/5656_2/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
APPLE_CFLAGS = 
APPLE_LIBS = -framework AudioToolbox -framework AudioUnit -framework VideoToolbox -framework CoreMedia -framework CoreFoundation -framework CoreVideo -framework CoreAudio
AR = ar
AUTOCONF = ${SHELL} /Users/taktod/Documents/c/5656_2/missing autoconf
AUTOHEADER = ${SHELL} /Users/taktod/Documents/c/5656_2/missing autoheader
AUTOMAKE = ${SHELL} /Users/taktod/Documents/c/5656_2/missing automake-1.15
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DAALADEC_CFLAGS = -I/usr/local/include/daala
DAALADEC_LIBS = -L/usr/local/lib -ldaaladec -ldaalabase
DAALAENC_CFLAGS = -I/usr/local/include/daala
DAALAENC_LIBS = -L/usr/local/lib -ldaalaenc -ldaalabase
DEFS = -DPACKAGE_NAME=\"ttLibC\" -DPACKAGE_TARNAME=\"ttlibc\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"ttLibC\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"ttlibc\" -DVERSION=\"1.0\" -D__ENABLE_MP3LAME__=1 -D__ENABLE_FAAC__=1 -D__ENABLE_FAAD__=1 -D__ENABLE_GPL__=1 -D__ENABLE_OPENCV__=1 -D__ENABLE_OPENAL__=1 -D__ENABLE_MP3LAME_DECODE__=1 -D__ENABLE_MP3LAME_ENCODE__=1 -D__ENABLE_FAAC_ENCODE__=1 -D__ENABLE_JPEG__=1 -D__ENABLE_OPENH264__=1 -D__ENABLE_SPEEXDSP__=1 -D__ENABLE_SPEEX__=1 -D__ENABLE_FILE__=1 -D__ENABLE_SOCKET__=1 -D__ENABLE_OPUS__=1 -D__ENABLE_AVCODEC__=1 -D__ENABLE_FAAD_DECODE__=1 -D__ENABLE_APPLE__=1 -D__ENABLE_X264__=1 -D__ENABLE_X265__=1 -D__ENABLE_THEORA__=1 -D__ENABLE_DAALA_ENCODE__=1 -D__ENABLE_DAALA_DECODE__=1 -D__ENABLE_VORBIS_ENCODE__=1 -D__ENABLE_VORBIS_DECODE__=1 -D__ENABLE_SOUNDTOUCH__=1 -D__ENABLE_FDKAAC__=1 -D__ENABLE_LIBYUV__=1 -D__ENABLE_SWSCALE__=1 -D__ENABLE_SWRESAMPLE__=1 -D__ENABLE_LIBPNG__=1
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EXEEXT = 
FAAC_CFLAGS = -I/usr/local/include
FAAC_LIBS = -L/usr/local/lib -lfaac
FAAD_CFLAGS = -I/usr/local/include
FAAD_LIBS = -L/usr/local/lib -lfaad
FDKAAC_CFLAGS = -I/usr/local/Cellar/fdk-aac/0.1.6/include
FDKAAC_LIBS = -L/usr/local/Cellar/fdk-aac/0.1.6/lib -lfdk-aac
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JPEG_CFLAGS = -I/usr/local/include
JPEG_LIBS = -L/usr/local/lib -ljpeg
LDFLAGS = 
LIBAVCODEC_CFLAGS = -I/usr/local/Cellar/ffmpeg/3.4.2/include
LIBAVCODEC_LIBS = -L/usr/local/Cellar/ffmpeg/3.4.2/lib -lavcodec -lavutil
LIBOBJS = 
LIBPNG_CFLAGS = -I/usr/local/Cellar/libpng/1.6.34/include/libpng16
LIBPNG_LIBS = -L/usr/local/Cellar/libpng/1.6.34/lib -lpng16 -lz
LIBS = 
LIBSWRESAMPLE_CFLAGS = -I/usr/local/Cellar/ffmpeg/3.4.2/include
LIBSWRESAMPLE_LIBS = -L/usr/local/Cellar/ffmpeg/3.4.2/lib -lswresample
LIBSWSCALE_CFLAGS = -I/usr/local/Cellar/ffmpeg/3.4.2/include
LIBSWSCALE_LIBS = -L/usr/local/Cellar/ffmpeg/3.4.2/lib -lswscale
LIBYUV_CFLAGS = -I/usr/local/include
LIBYUV_INCLUDE_PATH = /usr/local/include
LIBYUV_LIBS = -L/usr/local/lib -lyuv
LIBYUV_PATH = /usr/local/lib
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/taktod/Documents/c/5656_2/missing makeinfo
MKDIR_P = ./install-sh -c -d
MP3LAME_CFLAGS = -I/usr/local/include
MP3LAME_LIBS = -L/usr/local/lib -lmp3lame
OBJEXT = o
OPENAL_CFLAGS = 
OPENAL_LIBS = -framework OpenAL
OPENCV_CFLAGS = -I/usr/local/Cellar/opencv/3.4.1_2/include/opencv -I/usr/local/Cellar/opencv/3.4.1_2/include
OPENCV_LIBS = -L/usr/local/Cellar/opencv/3.4.1_2/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
OPENH264_CFLAGS = -I/usr/local/Cellar/openh264/1.7.0/include
OPENH264_LIBS = -L/usr/local/Cellar/openh264/1.7.0/lib -lopenh264
OPUS_CFLAGS = -I/usr/local/Cellar/opus/1.2.1/include/opus
OPUS_LIBS = -L/usr/local/Cellar/opus/1.2.1/lib -lopus
PACKAGE = ttlibc
PACKAGE_BUGREPORT = 
PACKAGE_NAME = ttLibC
PACKAGE_STRING = ttLibC 1.0
PACKAGE_TARNAME = ttlibc
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/local/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
SOUNDTOUCH_CFLAGS = -I/usr/local/Cellar/sound-touch/1.9.2/include/soundtouch
SOUNDTOUCH_LIBS = -L/usr/local/Cellar/sound-touch/1.9.2/lib -lSoundTouch
SPEEXDSP_CFLAGS = -I/usr/local/Cellar/speexdsp/1.2rc3/include
SPEEXDSP_LIBS = -L/usr/local/Cellar/speexdsp/1.2rc3/lib -lspeexdsp
SPEEX_CFLAGS = -I/usr/local/Cellar/speex/1.2.0/include
SPEEX_LIBS = -L/usr/local/Cellar/speex/1.2.0/lib -lspeex
STRIP = 
TEST_CFLAGS = -I/usr/local/include/cute_lib
TEST_LIBS = 
THEORA_CFLAGS = -I/usr/local/Cellar/theora/1.1.1/include -I/usr/local/Cellar/libogg/1.3.3/include
THEORA_LIBS = -L/usr/local/Cellar/theora/1.1.1/lib -L/usr/local/Cellar/libogg/1.3.3/lib -ltheora -logg
TTLIBC_DESCRIPTION = ttLibC library.
VERSION = 1.0
VORBISDEC_CFLAGS = -I/usr/local/Cellar/libvorbis/1.3.6/include -I/usr/local/Cellar/libogg/1.3.3/include
VORBISDEC_LIBS = -L/usr/local/Cellar/libvorbis/1.3.6/lib -lvorbis
VORBISENC_CFLAGS = -I/usr/local/Cellar/libvorbis/1.3.6/include -I/usr/local/Cellar/libogg/1.3.3/include
VORBISENC_LIBS = -L/usr/local/Cellar/libvorbis/1.3.6/lib -lvorbisenc
WEBRTC_CFLAGS = 
WEBRTC_INCLUDE_PATH = 
WEBRTC_LIBS = 
WEBRTC_PATH = /Users/taktod/tools/src/webrtc/src/out/DefaultNoDebug/
X264_CFLAGS = -I/usr/local/Cellar/x264/r2854/include
X264_LIBS = -L/usr/local/Cellar/x264/r2854/lib -lx264
X265_CFLAGS = -I/usr/local/Cellar/x265/2.7/include
X265_LIBS = -L/usr/local/Cellar/x265/2.7/lib -lx265
abs_builddir = /Users/taktod/Documents/c/5656_2
abs_srcdir = /Users/taktod/Documents/c/5656_2
abs_top_builddir = /Users/taktod/Documents/c/5656_2
abs_top_srcdir = /Users/taktod/Documents/c/5656_2
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin18.2.0
build_alias = 
build_cpu = x86_64
build_os = darwin18.2.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
debug_flag = 1
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin18.2.0
host_alias = 
host_cpu = x86_64
host_os = darwin18.2.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/taktod/Documents/c/5656_2/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgconfigdir = ${libdir}/pkgconfig
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-apple-darwin18.2.0
target_alias = 
target_cpu = x86_64
target_os = darwin18.2.0
target_vendor = apple
top_build_prefix = 
top_builddir = .
top_srcdir = .
nobase_include_HEADERS = ttLibC/container/container.h \
	ttLibC/container/flv.h ttLibC/container/mkv.h \
	ttLibC/container/mp3.h ttLibC/container/mp4.h \
	ttLibC/container/mpegts.h ttLibC/frame/audio/aac.h \
	ttLibC/frame/audio/adpcmImaWav.h ttLibC/frame/audio/audio.h \
	ttLibC/frame/audio/mp3.h ttLibC/frame/audio/nellymoser.h \
	ttLibC/frame/audio/opus.h ttLibC/frame/audio/pcmAlaw.h \
	ttLibC/frame/audio/pcmf32.h ttLibC/frame/audio/pcmMulaw.h \
	ttLibC/frame/audio/pcms16.h ttLibC/frame/audio/speex.h \
	ttLibC/frame/audio/vorbis.h ttLibC/frame/video/bgr.h \
	ttLibC/frame/video/flv1.h ttLibC/frame/video/h264.h \
	ttLibC/frame/video/h265.h ttLibC/frame/video/jpeg.h \
	ttLibC/frame/video/png.h ttLibC/frame/video/theora.h \
	ttLibC/frame/video/video.h ttLibC/frame/video/vp6.h \
	ttLibC/frame/video/vp8.h ttLibC/frame/video/vp9.h \
	ttLibC/frame/video/wmv1.h ttLibC/frame/video/wmv2.h \
	ttLibC/frame/video/yuv420.h ttLibC/frame/frame.h \
	ttLibC/resampler/audioResampler.h \
	ttLibC/resampler/imageResampler.h \
	ttLibC/resampler/imageResizer.h ttLibC/util/amfUtil.h \
	ttLibC/util/beepUtil.h ttLibC/util/byteUtil.h \
	ttLibC/util/crc32Util.h ttLibC/util/dynamicBufferUtil.h \
	ttLibC/util/hexUtil.h ttLibC/util/ioUtil.h \
	ttLibC/util/stlListUtil.h ttLibC/util/stlMapUtil.h \
	ttLibC/util/tetty2.h ttLibC/allocator.h ttLibC/log.h \
	ttLibC/ttLibC.h $(am__append_1) $(am__append_2) \
	$(am__append_3) $(am__append_4) $(am__append_5) \
	$(am__append_6) $(am__append_7) $(am__append_8) \
	$(am__append_9) $(am__append_10) $(am__append_11) \
	$(am__append_12) $(am__append_13) $(am__append_14) \
	$(am__append_15) $(am__append_16) $(am__append_17) \
	$(am__append_18) $(am__append_19) $(am__append_20) \
	$(am__append_21) $(am__append_22) $(am__append_23) \
	$(am__append_24)
pkgconfig_DATA = ttLibC.pc
CLEANFILES = ttLibC.pc
SUBDIRS = ttLibC cuteSrc
all: all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
ttLibC.pc: $(top_builddir)/config.status $(srcdir)/ttLibC.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(DATA) $(HEADERS)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-nobase_includeHEADERS install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-nobase_includeHEADERS uninstall-pkgconfigDATA

.MAKE: $(am__recursive_targets) install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-nobase_includeHEADERS \
	install-pdf install-pdf-am install-pkgconfigDATA install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
	pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-nobase_includeHEADERS uninstall-pkgconfigDATA

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
